/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.Pagamento;

import DTOs.pagamento.PagamentoDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;

/**
 *
 * @author i
 */
public class PagamentoCriarPainel extends PainelInterface {
    public PagamentoCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        PagamentoDTO pdto = new PagamentoDTO();

        String id = this.JTA_id.getText();
        String pedidoId = this.jTA_pedidoid.getText();
        String pix = this.jTA_pix.getText();
        String dinheiro = this.jTA_dinheiro.getText();
        String cartao = this.jTA_cartao.getText();

        if (pedidoId != null && !pedidoId.isEmpty()) {
            pdto.pedido = new Modelos.Pedido(Integer.valueOf(pedidoId), null, null, null, null, null);
        }
        if (pix != null && !pix.isEmpty()) {
            pdto.pix = Double.valueOf(pix);
        }
        if (dinheiro != null && !dinheiro.isEmpty()) {
            pdto.dinheiro = Double.valueOf(dinheiro);
        }
        if (cartao != null && !cartao.isEmpty()) {
            pdto.cartao = Double.valueOf(cartao);
        }

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }    
        return pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        PagamentoDTO pdto = (PagamentoDTO) dto;
        this.JTA_id.setText(String.valueOf(pdto.id));
        this.jTA_pedidoid.setText(String.valueOf(pdto.pedido != null ? pdto.pedido.getId() : ""));
        this.jTA_pix.setText(String.valueOf(pdto.pix != null ? pdto.pix : ""));
        this.jTA_dinheiro.setText(String.valueOf(pdto.dinheiro != null ? pdto.dinheiro : ""));
        this.jTA_cartao.setText(String.valueOf(pdto.cartao != null ? pdto.cartao : ""));
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_pedidoid.setText("");
        this.jTA_pix.setText("");
        this.jTA_dinheiro.setText("");
        this.jTA_cartao.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_pedidoid = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_pix = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_dinheiro = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTA_cartao = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Pedido ID");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_pedidoid.setColumns(20);
        jTA_pedidoid.setRows(1);
        jScrollPane2.setViewportView(jTA_pedidoid);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Valor pago em PIX");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_pix.setColumns(20);
        jTA_pix.setRows(1);
        jScrollPane3.setViewportView(jTA_pix);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Valor pago em Dinheiro");
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTA_dinheiro.setColumns(20);
        jTA_dinheiro.setRows(1);
        jScrollPane4.setViewportView(jTA_dinheiro);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.PAGE_END);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Valor pago por Cartão");
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTA_cartao.setColumns(20);
        jTA_cartao.setRows(1);
        jScrollPane5.setViewportView(jTA_cartao);

        jPanel5.add(jScrollPane5, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTA_cartao;
    private javax.swing.JTextArea jTA_dinheiro;
    private javax.swing.JTextArea jTA_pedidoid;
    private javax.swing.JTextArea jTA_pix;
    // End of variables declaration//GEN-END:variables
}
