/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.delivery;

import DTOs.delivery.EntregaDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;
import Modelos.delivery.endereco.Endereco;

/**
 *
 * @author i
 */
public class EntregaCriarPainel extends PainelInterface {
    public EntregaCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        EntregaDTO pdto = new EntregaDTO();

        String id = this.JTA_id.getText();
        String chave = this.jTA_chave.getText();
        String enderid = this.jTA_enderid.getText();
        String valor = this.jTA_valor.getText();

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }
        pdto.chave = chave;
        if (enderid != null && !enderid.isEmpty()) {
            pdto.endereco = new Endereco(Integer.valueOf(enderid), null, null, null, null, null);
        }
        if (valor != null && !valor.isEmpty()) {
            pdto.valor = Double.valueOf(valor);
        }
               
        return (InterfaceDTO) pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        EntregaDTO entregaDTO = (EntregaDTO) dto;
        this.JTA_id.setText(String.valueOf(entregaDTO.id));
        this.jTA_chave.setText(entregaDTO.chave);
        this.jTA_enderid.setText(String.valueOf(entregaDTO.endereco.getId()));
        this.jTA_valor.setText(String.valueOf(entregaDTO.valor));
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_chave.setText("");
        this.jTA_enderid.setText("");
        this.jTA_valor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_chave = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_enderid = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_valor = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(33, 200));
        setPreferredSize(new java.awt.Dimension(238, 200));
        setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Chave");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_chave.setColumns(20);
        jTA_chave.setRows(1);
        jScrollPane2.setViewportView(jTA_chave);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Endereço ID");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_enderid.setColumns(20);
        jTA_enderid.setRows(1);
        jScrollPane3.setViewportView(jTA_enderid);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Valor");
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTA_valor.setColumns(20);
        jTA_valor.setRows(1);
        jScrollPane4.setViewportView(jTA_valor);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.PAGE_END);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTA_chave;
    private javax.swing.JTextArea jTA_enderid;
    private javax.swing.JTextArea jTA_valor;
    // End of variables declaration//GEN-END:variables
}
