/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.delivery.endereco;

import DTOs.delivery.endereco.EnderecoDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;
import Modelos.delivery.endereco.Bairro;

/**
 *
 * @author i
 */
public class EnderecoCriarPainel extends PainelInterface {
    public EnderecoCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        EnderecoDTO dto = new EnderecoDTO();
        dto.id = this.JTA_id.getText().isEmpty() ? null : Integer.parseInt(this.JTA_id.getText());
        dto.cep = this.jTA_cep.getText();
        dto.bairro = new Bairro(this.jTA_idbairro.getText().isEmpty() ? null : Integer.parseInt(this.jTA_idbairro.getText()), null);
        dto.complemento = this.jTA_complemento.getText();
        dto.rua = this.jTA_rua.getText();
        dto.numero = this.jTA_numero.getText();
        return dto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        EnderecoDTO enderecoDTO = (EnderecoDTO) dto;
        this.JTA_id.setText(enderecoDTO.id == null ? "" : enderecoDTO.id.toString());
        this.jTA_cep.setText(enderecoDTO.cep);
        this.jTA_idbairro.setText(enderecoDTO.bairro.getId() != null ? enderecoDTO.bairro.getId().toString() : "");
        this.jTA_complemento.setText(enderecoDTO.complemento);
        this.jTA_rua.setText(enderecoDTO.rua);
        this.jTA_numero.setText(enderecoDTO.numero);
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_cep.setText("");
        this.jTA_idbairro.setText("");
        this.jTA_complemento.setText("");
        this.jTA_rua.setText("");
        this.jTA_numero.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_cep = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTA_idbairro = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_complemento = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_rua = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTA_numero = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("CEP");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_cep.setColumns(20);
        jTA_cep.setRows(1);
        jScrollPane3.setViewportView(jTA_cep);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("ID do Bairo");
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTA_idbairro.setColumns(20);
        jTA_idbairro.setRows(1);
        jScrollPane5.setViewportView(jTA_idbairro);

        jPanel5.add(jScrollPane5, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Complemento");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_complemento.setColumns(20);
        jTA_complemento.setRows(1);
        jScrollPane2.setViewportView(jTA_complemento);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Rua");
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTA_rua.setColumns(20);
        jTA_rua.setRows(1);
        jScrollPane4.setViewportView(jTA_rua);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.PAGE_END);

        add(jPanel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Numero");
        jPanel6.add(jLabel6, java.awt.BorderLayout.CENTER);

        jTA_numero.setColumns(20);
        jTA_numero.setRows(1);
        jScrollPane6.setViewportView(jTA_numero);

        jPanel6.add(jScrollPane6, java.awt.BorderLayout.PAGE_END);

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTA_cep;
    private javax.swing.JTextArea jTA_complemento;
    private javax.swing.JTextArea jTA_idbairro;
    private javax.swing.JTextArea jTA_numero;
    private javax.swing.JTextArea jTA_rua;
    // End of variables declaration//GEN-END:variables
}
