/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Controller.FuncionarioCTRL;
import Controller.StatusPedidoCTRL;
import Controller.carrinho.ingrediente.IngredienteCTRL;
import Controller.carrinho.produto.ProdutoCTRL;
import Controller.cliente.CartaoCTRL;
import Controller.cliente.ClienteCTRL;
import Controller.contato.TelefoneCTRL;
import Controller.delivery.EntregaCTRL;
import Controller.delivery.endereco.BairroCTRL;
import Controller.delivery.endereco.EnderecoCTRL;
import Controller.login.LoginCTRL;
import Interfaces.StatusPedidoCriarPainel;
import Interfaces.Carrinho.Ingrediente.IngredienteCriarPainel;
import Interfaces.Carrinho.Produto.ProdutoCriarPainel;
import Interfaces.FuncionarioCriarPainel;
import Interfaces.cliente.CartaoCriarPainel;
import Interfaces.cliente.ClienteCriarPainel;
import Interfaces.contato.TelefoneCriarPainel;
import Interfaces.delivery.EntregaCriarPainel;
import Interfaces.delivery.endereco.BairroCriarPainel;
import Interfaces.delivery.endereco.EnderecoCriarPainel;
import Interfaces.login.LoginCriarPainel;

/**
 *
 * @author i
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMB_Cadastros = new javax.swing.JMenu();
        jMBB_statuspedido = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMBB_logins = new javax.swing.JMenuItem();
        jMBB_funcionarios = new javax.swing.JMenuItem();
        jMBB_telefone = new javax.swing.JMenuItem();
        jMBB_clientes = new javax.swing.JMenuItem();
        jMBB_cartoesclientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMBB_bairro = new javax.swing.JMenuItem();
        jMBB_endereco = new javax.swing.JMenuItem();
        jMBB_entregas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMBB_ingredientes = new javax.swing.JMenuItem();
        jMBB_Produtos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sair");
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/ivanlogo3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMB_Cadastros.setText("Cadastros");

        jMBB_statuspedido.setText("Status Pedidos");
        jMBB_statuspedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_statuspedidoActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_statuspedido);
        jMB_Cadastros.add(jSeparator3);

        jMBB_logins.setText("Logins Funcionarios");
        jMBB_logins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_loginsActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_logins);

        jMBB_funcionarios.setText("Funcionarios");
        jMBB_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_funcionariosActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_funcionarios);

        jMBB_telefone.setText("Telefones");
        jMBB_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_telefoneActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_telefone);

        jMBB_clientes.setText("Clientes");
        jMBB_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_clientesActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_clientes);

        jMBB_cartoesclientes.setText("Cartoes Clientes");
        jMBB_cartoesclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_cartoesclientesActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_cartoesclientes);
        jMB_Cadastros.add(jSeparator1);

        jMBB_bairro.setText("Bairro");
        jMBB_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_bairroActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_bairro);

        jMBB_endereco.setText("Endereço");
        jMBB_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_enderecoActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_endereco);

        jMBB_entregas.setText("Entregas");
        jMBB_entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_entregasActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_entregas);
        jMB_Cadastros.add(jSeparator2);

        jMBB_ingredientes.setText("Ingredientes");
        jMBB_ingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_ingredientesActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_ingredientes);

        jMBB_Produtos.setText("Produtos");
        jMBB_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBB_ProdutosActionPerformed(evt);
            }
        });
        jMB_Cadastros.add(jMBB_Produtos);

        jMenuBar1.add(jMB_Cadastros);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMBB_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_ProdutosActionPerformed
        new CadastroGeral(null, false, new ProdutoCTRL(), new ProdutoCriarPainel());
    }//GEN-LAST:event_jMBB_ProdutosActionPerformed

    private void jMBB_ingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_ingredientesActionPerformed
        new CadastroGeral(null, false, new IngredienteCTRL(), new IngredienteCriarPainel());
    }//GEN-LAST:event_jMBB_ingredientesActionPerformed

    private void jMBB_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_bairroActionPerformed
        new CadastroGeral(null, false, new BairroCTRL(), new BairroCriarPainel());
    }//GEN-LAST:event_jMBB_bairroActionPerformed

    private void jMBB_loginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_loginsActionPerformed
        new CadastroGeral(null, false, new LoginCTRL(), new LoginCriarPainel());
    }//GEN-LAST:event_jMBB_loginsActionPerformed

    private void jMBB_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_telefoneActionPerformed
        new CadastroGeral(null, false, new TelefoneCTRL(), new TelefoneCriarPainel());
    }//GEN-LAST:event_jMBB_telefoneActionPerformed

    private void jMBB_statuspedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_statuspedidoActionPerformed
        new CadastroGeral(null, false, new StatusPedidoCTRL(), new StatusPedidoCriarPainel());
    }//GEN-LAST:event_jMBB_statuspedidoActionPerformed

    private void jMBB_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_enderecoActionPerformed
        new CadastroGeral(null, false, new EnderecoCTRL(), new EnderecoCriarPainel());
    }//GEN-LAST:event_jMBB_enderecoActionPerformed

    private void jMBB_entregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_entregasActionPerformed
        new CadastroGeral(null, false, new EntregaCTRL(), new EntregaCriarPainel()); 
    }//GEN-LAST:event_jMBB_entregasActionPerformed

    private void jMBB_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_funcionariosActionPerformed
        new CadastroGeral(null, false, new FuncionarioCTRL(), new FuncionarioCriarPainel());
    }//GEN-LAST:event_jMBB_funcionariosActionPerformed

    private void jMBB_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_clientesActionPerformed
        new CadastroGeral(null, false, new ClienteCTRL(), new ClienteCriarPainel());
    }//GEN-LAST:event_jMBB_clientesActionPerformed

    private void jMBB_cartoesclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBB_cartoesclientesActionPerformed
        new CadastroGeral(null, false, new CartaoCTRL(), new CartaoCriarPainel());
    }//GEN-LAST:event_jMBB_cartoesclientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMBB_Produtos;
    private javax.swing.JMenuItem jMBB_bairro;
    private javax.swing.JMenuItem jMBB_cartoesclientes;
    private javax.swing.JMenuItem jMBB_clientes;
    private javax.swing.JMenuItem jMBB_endereco;
    private javax.swing.JMenuItem jMBB_entregas;
    private javax.swing.JMenuItem jMBB_funcionarios;
    private javax.swing.JMenuItem jMBB_ingredientes;
    private javax.swing.JMenuItem jMBB_logins;
    private javax.swing.JMenuItem jMBB_statuspedido;
    private javax.swing.JMenuItem jMBB_telefone;
    private javax.swing.JMenu jMB_Cadastros;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
