/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.Carrinho;

import DTOs.carrinho.CarrinhoDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;
import Modelos.Pedido;
import Modelos.carrinho.produto.Produto;

/**
 *
 * @author i
 */
public class CarrinhoCriarPainel extends PainelInterface {
    public CarrinhoCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        CarrinhoDTO pdto = new CarrinhoDTO();

        String id = this.JTA_id.getText();
        String produtoId = this.jTA_produtoid.getText();
        String pedidoId = this.jTA_pedidoid.getText();
        String quantidade = this.jTA_quantidade.getText();

        if (produtoId != null && !produtoId.isEmpty()) {
            pdto.produto = new Produto(Integer.valueOf(produtoId), null, null);
        }
        if (pedidoId != null && !pedidoId.isEmpty()) {
            pdto.pedido = new Pedido(Integer.valueOf(pedidoId), null, null, null, null, null);
        }
        if (quantidade != null && !quantidade.isEmpty()) {
            pdto.quantidade = Integer.valueOf(quantidade);
        }

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }    
        return (InterfaceDTO) pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        CarrinhoDTO pdto = (CarrinhoDTO) dto;
        this.JTA_id.setText(String.valueOf(pdto.id));
        this.jTA_produtoid.setText(String.valueOf(pdto.produto.getId()));
        this.jTA_pedidoid.setText(String.valueOf(pdto.pedido.getId()));
        this.jTA_quantidade.setText(String.valueOf(pdto.quantidade));
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_produtoid.setText("");
        this.jTA_pedidoid.setText("");
        this.jTA_quantidade.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_produtoid = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_pedidoid = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTA_quantidade = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Produto ID");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_produtoid.setColumns(20);
        jTA_produtoid.setRows(1);
        jScrollPane2.setViewportView(jTA_produtoid);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Pedido ID");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_pedidoid.setColumns(20);
        jTA_pedidoid.setRows(1);
        jScrollPane3.setViewportView(jTA_pedidoid);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Quantidade");
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTA_quantidade.setColumns(20);
        jTA_quantidade.setRows(1);
        jScrollPane5.setViewportView(jTA_quantidade);

        jPanel5.add(jScrollPane5, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTA_pedidoid;
    private javax.swing.JTextArea jTA_produtoid;
    private javax.swing.JTextArea jTA_quantidade;
    // End of variables declaration//GEN-END:variables
}
