/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.cliente;

import DTOs.cliente.CartaoDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;
import Modelos.cliente.Cliente;

/**
 *
 * @author i
 */
public class CartaoCriarPainel extends PainelInterface {
    public CartaoCriarPainel() {
        initComponents();
        this.jRB_credito.setSelected(true);
    }
    
    @Override
    public InterfaceDTO getData() {
        CartaoDTO pdto = new CartaoDTO();

        String id = this.JTA_id.getText();
        String numero = this.jTA_numero.getText();
        String cvv = this.jTA_cvv.getText();
        Boolean isCredito = this.jRB_credito.isSelected();
        String clienteid = this.jTA_clienteid.getText();

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }
        pdto.numero = numero;
        if (cvv != null && !cvv.isEmpty()) {
            pdto.CVV = Integer.valueOf(cvv);
        }
        pdto.isCredito = isCredito;
        if (clienteid != null && !clienteid.isEmpty()) {
            pdto.cliente = new Cliente(Integer.valueOf(clienteid), null, null);
        }
               
        return pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        this.JTA_id.setText(String.valueOf(((CartaoDTO) dto).id));
        this.jTA_numero.setText(((CartaoDTO) dto).numero);
        this.jTA_cvv.setText(String.valueOf(((CartaoDTO) dto).CVV));
        this.jRB_credito.setSelected(((CartaoDTO) dto).isCredito);
        this.jRB_debito.setSelected(!((CartaoDTO) dto).isCredito);
        this.jTA_clienteid.setText(String.valueOf(((CartaoDTO) dto).cliente.getId()));
    }
    
    
    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_numero.setText("");
        this.jTA_cvv.setText("");
        this.jRB_credito.setSelected(false);
        this.jRB_debito.setSelected(false);
        this.jTA_clienteid.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoescredito = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_numero = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_cvv = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRB_credito = new javax.swing.JRadioButton();
        jRB_debito = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_clienteid = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Numero");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_numero.setColumns(20);
        jTA_numero.setRows(1);
        jScrollPane2.setViewportView(jTA_numero);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("CVV");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_cvv.setColumns(20);
        jTA_cvv.setRows(1);
        jScrollPane3.setViewportView(jTA_cvv);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jLabel4.setText("Tipo: ");
        jPanel4.add(jLabel4);

        botoescredito.add(jRB_credito);
        jRB_credito.setText("Credito");
        jRB_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_creditoActionPerformed(evt);
            }
        });
        jPanel4.add(jRB_credito);

        botoescredito.add(jRB_debito);
        jRB_debito.setText("Debito");
        jPanel4.add(jRB_debito);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Cliente ID");
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTA_clienteid.setColumns(20);
        jTA_clienteid.setRows(1);
        jScrollPane4.setViewportView(jTA_clienteid);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents

    private void jRB_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_creditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_creditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.ButtonGroup botoescredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRB_credito;
    private javax.swing.JRadioButton jRB_debito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTA_clienteid;
    private javax.swing.JTextArea jTA_cvv;
    private javax.swing.JTextArea jTA_numero;
    // End of variables declaration//GEN-END:variables
}
