/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.cliente;

import DTOs.cliente.ClienteDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;
import Modelos.contato.Telefone;

/**
 *
 * @author i
 */
public class ClienteCriarPainel extends PainelInterface {
    public ClienteCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        ClienteDTO pdto = new ClienteDTO();

        String id = this.JTA_id.getText();
        String nome = this.jTA_nome.getText();
        String telefoneid = this.jTA_telefoneid.getText();

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }
        pdto.nome = nome;
        if (telefoneid != null && !telefoneid.isEmpty()) {
            pdto.telefone = new Telefone(Integer.valueOf(telefoneid), null, null);
        }
               
        return (InterfaceDTO) pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        this.JTA_id.setText(String.valueOf(((ClienteDTO) dto).id));
        this.jTA_nome.setText(((ClienteDTO) dto).nome);
        this.jTA_telefoneid.setText(String.valueOf(((ClienteDTO) dto).telefone.getId()));
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_nome.setText("");
        this.jTA_telefoneid.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_nome = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_telefoneid = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_nome.setColumns(20);
        jTA_nome.setRows(1);
        jScrollPane2.setViewportView(jTA_nome);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Telefone ID");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_telefoneid.setColumns(20);
        jTA_telefoneid.setRows(1);
        jScrollPane3.setViewportView(jTA_telefoneid);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTA_nome;
    private javax.swing.JTextArea jTA_telefoneid;
    // End of variables declaration//GEN-END:variables
}
