/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import DTOs.FuncionarioDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;
import Modelos.contato.Telefone;
import Modelos.login.Login;

/**
 *
 * @author i
 */
public class FuncionarioCriarPainel extends PainelInterface {
    public FuncionarioCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        FuncionarioDTO pdto = new FuncionarioDTO();

        String id = this.JTA_id.getText();
        String nome = this.jTA_nome.getText();
        String telefoneid = this.jTA_telefoneid.getText();
        String loginid = this.jTA_loginid.getText();
        String cpf = this.jTA_cpf.getText();
        String rg = this.jTA_rg.getText();


        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }
        pdto.nome = nome;
        if (telefoneid != null && !telefoneid.isEmpty()) {
            pdto.telefone = new Telefone(Integer.valueOf(telefoneid), null, null);
        }
        if (loginid != null && !loginid.isEmpty()) {
            pdto.login = new Login(Integer.valueOf(loginid), null, null);
        }
        pdto.cpf = cpf;
        pdto.rg = rg;
                   
        return pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        FuncionarioDTO funcionarioDTO = (FuncionarioDTO) dto;
        this.JTA_id.setText(String.valueOf(funcionarioDTO.id));
        this.jTA_nome.setText(funcionarioDTO.nome);
        this.jTA_telefoneid.setText(String.valueOf(funcionarioDTO.telefone.getId()));
        this.jTA_loginid.setText(String.valueOf(funcionarioDTO.login.getId()));
        this.jTA_cpf.setText(funcionarioDTO.cpf);
        this.jTA_rg.setText(funcionarioDTO.rg);
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_nome.setText("");
        this.jTA_telefoneid.setText("");
        this.jTA_loginid.setText("");
        this.jTA_cpf.setText("");
        this.jTA_rg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_nome = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_telefoneid = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_loginid = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTA_cpf = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTA_rg = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_nome.setColumns(20);
        jTA_nome.setRows(1);
        jScrollPane2.setViewportView(jTA_nome);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Telefone ID");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_telefoneid.setColumns(20);
        jTA_telefoneid.setRows(1);
        jScrollPane3.setViewportView(jTA_telefoneid);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Login ID");
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTA_loginid.setColumns(20);
        jTA_loginid.setRows(1);
        jScrollPane4.setViewportView(jTA_loginid);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.PAGE_END);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("CPF");
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTA_cpf.setColumns(20);
        jTA_cpf.setRows(1);
        jScrollPane5.setViewportView(jTA_cpf);

        jPanel5.add(jScrollPane5, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("RG");
        jPanel6.add(jLabel6, java.awt.BorderLayout.CENTER);

        jTA_rg.setColumns(20);
        jTA_rg.setRows(1);
        jScrollPane6.setViewportView(jTA_rg);

        jPanel6.add(jScrollPane6, java.awt.BorderLayout.PAGE_END);

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTA_cpf;
    private javax.swing.JTextArea jTA_loginid;
    private javax.swing.JTextArea jTA_nome;
    private javax.swing.JTextArea jTA_rg;
    private javax.swing.JTextArea jTA_telefoneid;
    // End of variables declaration//GEN-END:variables
}
