/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import DTOs.StatusPedidoDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;

/**
 *
 * @author i
 */
public class StatusPedidoCriarPainel extends PainelInterface {
    public StatusPedidoCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        StatusPedidoDTO pdto = new StatusPedidoDTO();

        String id = this.JTA_id.getText();
        String progresso = this.jTA_progresso.getText();

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.parseInt(id);
        }
        pdto.progresso = progresso;
        
        return (InterfaceDTO) pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        this.JTA_id.setText(String.valueOf(((StatusPedidoDTO) dto).id));
        this.jTA_progresso.setText(((StatusPedidoDTO) dto).progresso);
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_progresso.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_progresso = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nome progresso");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_progresso.setColumns(20);
        jTA_progresso.setRows(1);
        jScrollPane2.setViewportView(jTA_progresso);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA_progresso;
    // End of variables declaration//GEN-END:variables
}
