/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.Carrinho.Ingrediente;

import DTOs.carrinho.ingrediente.IngredienteEscolhaDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;

/**
 *
 * @author i
 */
public class IngredienteEscolhaCriarPainel extends PainelInterface {
    public IngredienteEscolhaCriarPainel() {
        initComponents();
        
        this.jRB_adicionar.setSelected(true);
    }
    
    @Override
    public InterfaceDTO getData() {
        IngredienteEscolhaDTO pdto = new IngredienteEscolhaDTO();

        String id = this.JTA_id.getText();
        String ingredienteID = this.jTA_ingredienteid.getText();
        String carrinhoID = this.jTA_carrinhoID.getText();
        Boolean toExclude = this.jRB_excluir.isSelected();
        
        if (ingredienteID != null && !ingredienteID.isEmpty()) {
            pdto.ingrediente = new Modelos.carrinho.ingrediente.Ingrediente(Integer.valueOf(ingredienteID), null, null);
        }
        if (carrinhoID != null && !carrinhoID.isEmpty()) {
            pdto.carrinho = new Modelos.carrinho.Carrinho(Integer.valueOf(carrinhoID), null, null, null);
        }
        
        pdto.toExclude = toExclude;

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }    
        return (InterfaceDTO) pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        IngredienteEscolhaDTO pdto = (IngredienteEscolhaDTO) dto;
        this.JTA_id.setText(String.valueOf(pdto.id));
        this.jTA_ingredienteid.setText(String.valueOf(pdto.ingrediente.getId()));
        this.jTA_carrinhoID.setText(String.valueOf(pdto.carrinho.getId()));
        this.jRB_adicionar.setSelected(!pdto.toExclude);
        this.jRB_excluir.setSelected(pdto.toExclude);
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_ingredienteid.setText("");
        this.jTA_carrinhoID.setText("");
        this.jRB_adicionar.setSelected(true);
        this.jRB_excluir.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_ingredienteid = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_carrinhoID = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRB_adicionar = new javax.swing.JRadioButton();
        jRB_excluir = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Ingrediente ID");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_ingredienteid.setColumns(20);
        jTA_ingredienteid.setRows(1);
        jScrollPane2.setViewportView(jTA_ingredienteid);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Carrinho ID");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_carrinhoID.setColumns(20);
        jTA_carrinhoID.setRows(1);
        jScrollPane3.setViewportView(jTA_carrinhoID);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jLabel4.setText("Ação: ");
        jPanel4.add(jLabel4);

        buttonGroup1.add(jRB_adicionar);
        jRB_adicionar.setText("Adicionar");
        jRB_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_adicionarActionPerformed(evt);
            }
        });
        jPanel4.add(jRB_adicionar);

        buttonGroup1.add(jRB_excluir);
        jRB_excluir.setText("Excluir");
        jPanel4.add(jRB_excluir);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void jRB_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_adicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_adicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRB_adicionar;
    private javax.swing.JRadioButton jRB_excluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTA_carrinhoID;
    private javax.swing.JTextArea jTA_ingredienteid;
    // End of variables declaration//GEN-END:variables
}
