/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.Pagamento.cupom;

import DTOs.pagamento.cupom.CupomDTO;
import Interfaces.InterfaceDTO;
import Interfaces.PainelInterface;

/**
 *
 * @author i
 */
public class CupomCriarPainel extends PainelInterface {
    public CupomCriarPainel() {
        initComponents();
    }
    
    @Override
    public InterfaceDTO getData() {
        CupomDTO pdto = new CupomDTO();

        String id = this.JTA_id.getText();
        String valor = this.jTA_valor.getText();
        String codigo = this.jTA_codigo.getText();
        String validade = this.jTA_validade.getText();
        String pagamentoId = this.jTA_pagamentoid.getText();

        if (valor != null && !valor.isEmpty()) {
            pdto.valor = Double.valueOf(valor);
        }
        if (codigo != null && !codigo.isEmpty()) {
            pdto.codigo = String.valueOf(codigo);
        }
        if (validade != null && !validade.isEmpty()) {
            pdto.validade = String.valueOf(validade);
        }
        if (pagamentoId != null && !pagamentoId.isEmpty()) {
            pdto.pagamento = new Modelos.pagamento.Pagamento(Integer.valueOf(pagamentoId), null, null, null, null);
        }

        if (id != null && !id.isEmpty()) {
            pdto.id = Integer.valueOf(id);
        }    
        return pdto;
    }
    
    @Override
    public void setDados(InterfaceDTO dto) {
        CupomDTO pdto = (CupomDTO) dto;
        this.JTA_id.setText(String.valueOf(pdto.id));
        this.jTA_valor.setText(String.valueOf(pdto.valor));
        this.jTA_codigo.setText(String.valueOf(pdto.codigo));
        this.jTA_validade.setText(String.valueOf(pdto.validade));
        this.jTA_pagamentoid.setText(String.valueOf(pdto.pagamento != null ? pdto.pagamento.getId() : ""));
    }

    @Override
    public void clear() {
        this.JTA_id.setText("");
        this.jTA_valor.setText("");
        this.jTA_codigo.setText("");
        this.jTA_validade.setText("");
        this.jTA_pagamentoid.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_id = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_valor = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTA_codigo = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTA_validade = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTA_pagamentoid = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        JTA_id.setColumns(20);
        JTA_id.setRows(1);
        jScrollPane1.setViewportView(JTA_id);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Valor do cupom");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTA_valor.setColumns(20);
        jTA_valor.setRows(1);
        jScrollPane2.setViewportView(jTA_valor);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Codigo do cupom");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTA_codigo.setColumns(20);
        jTA_codigo.setRows(1);
        jScrollPane3.setViewportView(jTA_codigo);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Validade");
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTA_validade.setColumns(20);
        jTA_validade.setRows(1);
        jScrollPane4.setViewportView(jTA_validade);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.PAGE_END);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Ref ao Pagamento ID");
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTA_pagamentoid.setColumns(20);
        jTA_pagamentoid.setRows(1);
        jScrollPane5.setViewportView(jTA_pagamentoid);

        jPanel5.add(jScrollPane5, java.awt.BorderLayout.PAGE_END);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTA_codigo;
    private javax.swing.JTextArea jTA_pagamentoid;
    private javax.swing.JTextArea jTA_validade;
    private javax.swing.JTextArea jTA_valor;
    // End of variables declaration//GEN-END:variables
}
